#' check the ppm error for the intense peaks of MS/MS
#'
#'
#' @export
#'
#' @param RT_mass it is a list of data frame, obtained by check_RT_mass() function. it is contains a list of metabolite with desired retention time and PPM error. each metabolite is a data frame of potential candidates with specific features; Feature_ID, RT_err, RT_flag, ppm_error, mass_status and mass_flag.
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param RI_sample it is generated by RI_sample_data() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks.
#' @param reference A list of metabolite with their specific features of retention time and mz which stored by their ID, CAS number and Name.
#' @param lib_peaks_data it is generated by select_library() function. it is providing information regarding the peaks such as ID, CAS number, Name and POS/NEG collision energy.
#' @param n_peaks A number with default value of 1. check_intense_peak() function calculate the PPM error peak by peak starting from the most intense one. n_peaks is the number of the peaks which will be calculated for each metabolite and candidate.
#' @param acceptable_PPM_err A number with default value of 10. The maximum PPM error must be less than this value. and those above this number will be eliminated.
#' @param mode mode could be set in positive or negative state. positive mode select positive collision energy and mz in positive mode.
#'
check_intense_peak2 <- function(RT_mass=NULL, RI_lib=NULL , RI_sample=NULL, reference=NULL, lib_peaks_data=NULL, n_peaks=1, acceptable_PPM_err = 10, mode=c("POS", "NEG")) {

  #ensure the same order
  lib_peaks_data <- lib_peaks_data[match(names(RI_lib), lib_peaks_data$ID), ]

  for(z in 1:length(RT_mass)){
    cat("processing z", z, "\n")
    CAS_z <- reference$CAS[reference$ID == names(RT_mass)[z]]
    z_peaks_all <- RI_lib[lib_peaks_data$CAS == CAS_z & lib_peaks_data$Collision_energy == mode ]

    if(length(z_peaks_all)>0){

      for(zzzz in 1:length(z_peaks_all)){
        z_peaks <- as.data.frame(z_peaks_all[[zzzz]])

        for(zi in 1:nrow(RT_mass[[z]])){
          zi_peaks <- as.data.frame(RI_sample[names(RI_sample) == RT_mass[[z]]$Feature_ID[zi]])

          cat("processing zi", zi, "\n")

          #the first
          table_values_a <- sort(unique(z_peaks[, 2]), decreasing = T) #library peaks
          table_values_b <- sort(unique(zi_peaks[, 2]), decreasing = T) #sample peaks

          temp_flag_peaks <- rep(FALSE, n_peaks)

          for(ii in 1:min(n_peaks, length(table_values_a))){

            a = z_peaks[z_peaks[,2] == table_values_a[ii], , drop=FALSE]
            if(length(table_values_b) < ii){
              break
            }
            b = zi_peaks[zi_peaks[,2] == table_values_b[ii], , drop=FALSE]

            PPM_err <- calc_ppm_err(a, b)

            temp_flag_peaks[ii] <- any(PPM_err < acceptable_PPM_err)

            #ifelse(temp_flag_peaks[ii] == T, RT_mass[[z]]$intense_peaks<- all(temp_flag_peaks) , break)

            if(!temp_flag_peaks[ii]){ #if FALSE avoid the comparison for the next peaks
              break
            }
          }

            RT_mass[[z]]$intense_peaks <- all(temp_flag_peaks)
            RT_mass[[z]]$ID <- names(RT_mass)[z]
            RT_mass[[z]]$ID_peaks <- names(z_peaks_all)[zzzz]

      }
    }
    }
  }


  #filtering RT_mass by deleting the candidates with bad ppm error
  abc <- RT_mass[sapply(RT_mass, function(x) dim(x)[2] > 8)]

  if(length(abc)>0){

  abc <- do.call(rbind, abc)

  abc <- abc[!(abc$intense_peaks == FALSE), ]

  abc <- merge(x= abc, y= lib_peaks_data, by.x="ID_peaks", by.y="ID", all.x=T)
  colnames(abc)[colnames(abc) == "Name"] <- "Name_peaks"
  abc <- merge(x= abc, y=reference, by=c("ID", "CAS"), all.x=T)
}
  return(abc)

}
