#' check the ppm error for the intense peaks of MS/MS
#'
#'
#' @export
#'
#' @param RT_mass it is a list of data frame, obtained by check_RT_mass() function. it is contains a list of metabolite with desired retention time and PPM error. each metabolite is a data frame of potential candidates with specific features; Feature_ID, RT_err, RT_flag, ppm_error, mass_status and mass_flag.
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param RI_sample RI_sample
#' @param reference reference
#' @param lib_peaks_data lib_peaks_data
#' @param n_peaks n_peaks 
#' @param acceptable_PPM_err acceptable_PPM_err
#' @param mode mode
#'
check_intense_peak2 <- function(RT_mass=NULL, RI_lib=NULL , RI_sample=NULL, reference=NULL, lib_peaks_data=NULL, n_peaks=1, acceptable_PPM_err = 10, mode=c("POS", "NEG")) {

  #ensure the same order
  lib_peaks_data <- lib_peaks_data[match(names(RI_lib), lib_peaks_data$ID), ]

  for(z in 1:length(RT_mass)){

    CAS_z <- reference$CAS[reference$ID == names(RT_mass)[z]]
    z_peaks_all <- RI_lib[lib_peaks_data$CAS == CAS_z & lib_peaks_data$Collision_energy == mode ]

    if(length(z_peaks_all)>0){

      for(zzzz in 1:length(z_peaks_all)){
        z_peaks <- as.data.frame(z_peaks_all[[zzzz]])

        RT_mass[[z]]$ID_peaks <- names(z_peaks_all)[zzzz]

        for(zi in 1:nrow(RT_mass[[z]])){
          zi_peaks <- as.data.frame(RI_sample[names(RI_sample) == RT_mass[[z]]$Feature_ID[zi]])

          cat("processing zi", zi, "\n")

          #the first
          table_values_a <- sort(unique(z_peaks[, 2]), decreasing = T) #library peaks
          table_values_b <- sort(unique(zi_peaks[, 2]), decreasing = T) #sample peaks

          temp_flag_peaks <- rep(FALSE, n_peaks)
          for(ii in 1:min(n_peaks, length(table_values_a))){

            a = z_peaks[z_peaks[,2] == table_values_a[ii], , drop=FALSE]
            if(length(table_values_b) < ii){
              break
            }
            b = zi_peaks[zi_peaks[,2] == table_values_b[ii], , drop=FALSE]

            PPM_err <- calc_ppm_err(a, b)

            temp_flag_peaks[ii] <- any(PPM_err < acceptable_PPM_err)

            if(!temp_flag_peaks[ii]){ #if FALSE avoid the comparison for the next peaks
              break
            }

            RT_mass[[z]]$intense_peaks <- all(temp_flag_peaks)
            RT_mass[[z]]$ID <- names(RT_mass)[z]
          }
        }
      }
    }
  }

  #filtering RT_mass by deleting the candidates with bad ppm error
  RT_mass <- RT_mass[sapply(RT_mass, function(x) dim(x)[2] > 8)]

  abc <- do.call(rbind, RT_mass)


  abc <- merge(x= as.data.frame(abc), y= as.data.frame(lib_peaks_data), by.x="ID_peaks", by.y="ID", all.x=T)
  colnames(abc)[colnames(abc) == "Name"] <- "Name_peaks"
  abc <- merge(x= as.data.frame(abc), y=as.data.frame(reference), by="ID")

  return(abc)

}
