#' Find metabolite families
#' @export
#' @param reference an object structured as the element "lib_precursor" of the list returned by margherita_library()
#' @param feature_data an object structured as the elment "metab_ann" of the mRList object
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param RI_sample it is generated by RI_sample_data() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks.
#' @param lib_peaks_data it is generated by select_library() function. it is providing information regarding the peaks such as ID, CAS number, Name and POS/NEG collision energy.
#' @param rt_err_thr threshold over the retention time error
#' @param unaccept_flag A number with default value of 15. The maximum PPM error must be less than this value. and those above this number will be eliminated.
#' @param mode mode could be set in positive or negative state. positive mode select positive collision energy and mz in positive mode.
#' @param ppm_err A number with default value of 10. The maximum PPM error must be less than this value. and those above this number will be eliminated.
#' @param intensity maximum relative intensity
#' 
metabolite_family <- function(reference=NULL, feature_data=NULL, RI_lib=NULL, RI_sample=NULL, lib_peaks_data=NULL, rt_err_thr=1, unaccept_flag= 10, mode=c("NEG","POS"), ppm_err=10, intensity=30){

RT <- check_RT(reference=reference, feature_data=feature_data, rt_err_thr=rt_err_thr)

#mass <- check_mass2(reference=reference, feature_data=feature_data ,unaccept_flag=unaccept_flag)

mass <- check_mass(reference=reference, feature_data=feature_data ,unaccept_flag=unaccept_flag)

RT_mass <- check_RT_mass(RT=RT , mass=mass , reference=reference)

match_peaks <- peak_matching(reference=reference ,RT_mass=RT_mass, RI_lib=RI_lib ,RI_sample=RI_sample ,lib_peaks_data=lib_peaks_data, mode=mode, ppm_err=ppm_err, intensity=intensity)

return(match_peaks)

}
