#' Visualize the spectra of good candidates
#'
#' @param feature_id feature id
#' @param peak_id peak id
#' @param RI_sample it is generated by RI_sample_data() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks.
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param out_dir output directory
#' @export
#' @importFrom graphics par lines legend
#' @importFrom grDevices jpeg adjustcolor
#' @importFrom plotrix thigmophobe.labels
#' @importFrom Hmisc minor.tick
#' @param lib_peaks_data it is generated by select_library() function. it is providing information regarding the peaks such as ID, CAS number, Name and POS/NEG collision energy.
#' @param type mirrored or overlapped visualization
#' @param match_matrix matrix with matches
#' @param peak_number whether to show the peak number or not

visualize_1spectra <- function(feature_id=NULL, peak_id=NULL, RI_sample=NULL, RI_lib = NULL, lib_peaks_data=NULL, out_dir="./", type=c("mirrored", "overlapped"), match_matrix=NULL, peak_number=FALSE){
  
  type <- match.arg(type)
  feature_spectra <- RI_sample[[as.character(feature_id)]]
  library_spectra <- RI_lib[[as.character(peak_id)]]
  
  
  dir.create(out_dir, recursive = T)
  
  jpeg(filename = paste0(out_dir, "/", feature_id, "_",  peak_id, ".jpg"), width = 200, height = 200, res=300, units = "mm")
  
  if(type=="mirrored"){
    ylim <- c(-100, 100)
    hlines <- seq(-100, 100, 10)
  }else{
    ylim <- c(0, 100)
    hlines <- seq(0, 100, 10)
  }
  
  #empty plot
  plot(0, pch="", xlim=c(min(library_spectra[, 1], feature_spectra[, 1]), max(library_spectra[, 1], feature_spectra[, 1])), ylim = ylim, xlab = "m/z", ylab = "Relative Intensity")
  abline(h=hlines, lty=2, col="gray")
  minor.tick(ny = 2, nx=1)
  
  #library
  points(library_spectra[, 1] , library_spectra[, 2], type = "h" , col= adjustcolor("red", 0.6), lwd=2)
  points(library_spectra[, 1], library_spectra[,2], col=adjustcolor("red", 0.8), pch=16)
  
  if(peak_number){
    plotrix::thigmophobe.labels(library_spectra[, 1], library_spectra[,2], 1:nrow(library_spectra))
  }
  
  ### feature
  if(type=="mirrored"){
    
    lines(feature_spectra[, 1], -feature_spectra[,2], type = "h" , col=adjustcolor("blue", 0.6))
    points(feature_spectra[, 1], -feature_spectra[,2], col=adjustcolor("blue", 0.6), pch=16)
    if(peak_number){
      plotrix::thigmophobe.labels(feature_spectra[, 1], -feature_spectra[, 2], 1:nrow(feature_spectra))
    }
    
  }else{
    
    lines(feature_spectra[, 1], feature_spectra[,2], type = "h" , col=adjustcolor("blue", 0.6), lwd=2)
    points(feature_spectra[, 1], feature_spectra[,2], col=adjustcolor("blue", 0.6), pch=16)
    if(peak_number){
      plotrix::thigmophobe.labels(feature_spectra[, 1], feature_spectra[, 2], 1:nrow(feature_spectra))
    }
    
  }
  

  if(!is.null(match_matrix)){
    lib_n <- which(apply(match_matrix, 1, function(x) any(x==3)))
    points(library_spectra[lib_n, 1], rep(0, length(lib_n)), pch="X", col="red", cex=2)
  }
  
  legend("bottomright", legend=c(lib_peaks_data$Name[lib_peaks_data$ID==peak_id], feature_id), lty=1, col=c("red", "blue"), cex=0.7, bg="transparent") 
  
  dev.off()
  
}
