#' Visualize the spectra of good candidates
#' @param x candidates
#' @param RI_sample it is generated by RI_sample_data() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks.
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param dir_out output directory
#' @export
#' @importFrom graphics par lines
#' @importFrom grDevices jpeg

visualize_spectra2 <- function(x=NULL, RI_sample=NULL, RI_lib=NULL, dir_out="./"){
  
  for(a in 1: length(x)){ # cycle thought library metabolites
    lib_plot <- as.data.frame(RI_lib[names(RI_lib) == x[[a]]$ID_peaks[a]])
    
    jpeg(filename = paste0(dir_out, "/", x[[a]]$ID_peaks[a], ".jpg"))
    
    #if(nrow(x[[a]])>1){
    #par(mfrow = c(round(nrow(x[[a]])/2), round(nrow(x[[a]])/2)+1))
    #}else{par(mfrow = c(round(nrow(x[[a]])/2)+1, round(nrow(x[[a]])/2)+1))}
    
    if(nrow(x[[a]])<7){
      par(mfrow = c(2,3))
    }else{par(mfrow = c(3,3))}
    
    for(b in 1:nrow(x[[a]])){ #cycle through candidates
      sample_plot <- as.data.frame(RI_sample[names(RI_sample) == x[[a]]$Feature_ID[b]])
      
      if(length(lib_plot)>0){
        plot(lib_plot[,1] , lib_plot[,2] ,
             xlim=c(min(lib_plot[ ,1], sample_plot[ ,1]), max(lib_plot[ ,1], sample_plot[ ,1])),
             ylim = c(-100, 100),
             type = "h" , col= "red" ,
             xlab = names(sample_plot)[1] , ylab = "Relative Intensity",
             main= unique(x[[a]]$Name), font.main= 2 , cex.main= 0.9 )
        
        lines( sample_plot[ ,1], -sample_plot[ ,2], type = "h" , col="blue")
      }
    }
    dev.off()
  }
  return()
  
}
