#' Visualize the spectra of good candidates
#'
#' @param feature_id feature id
#' @param peak_id peak id
#' @param RI_sample it is generated by RI_sample_data() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks.
#' @param RI_lib it is generated by RI_lib_data() or select_library() function in order to turn intensity to relative intensity and filter the spectra by deleting the low intense peaks. note that in house library of the margheRita is already stored by relative intensity and filtered by select_library() function so, in this case RI_lib is lib_peaks which is generated by select_library() function.
#' @param out_dir output directory
#' @export
#' @importFrom graphics par lines
#' @importFrom grDevices jpeg

visualize_1spectra <- function(feature_id=NULL, peak_id=NULL, RI_sample=NULL, RI_lib = NULL, lib_peaks_data=NULL, out_dir="./"){
  
  feature_spectra <- RI_sample[[as.character(feature_id)]]
  library_spectra <- RI_lib[[as.character(peak_id)]]
  
  dir.create(out_dir, recursive = T)
  
  jpeg(filename = paste0(out_dir, "/", feature_id, "_",  peak_id, ".jpg"), width = 200, height = 200, res=300, units = "mm")
  
  plot(library_spectra[, 1] , library_spectra[, 2], xlim=c(min(library_spectra[, 1], feature_spectra[, 1]), max(library_spectra[, 1], feature_spectra[, 1])), ylim = c(-100, 100), type = "h" , col= "red" , xlab = "m/z", ylab = "Relative Intensity")
  lines(feature_spectra[, 1], -feature_spectra[,2], type = "h" , col="blue")
  legend("bottomright", legend=c(lib_peaks_data$Name[lib_peaks_data$ID==peak_id], feature_id), lty=1, col=c("red", "blue"), cex=0.7, bg="transparent") 
  
  dev.off()
  
}
